[package]
name = "vm"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "^1"
lazy_static = "^1"
tokio = { version = "^1", features = ["full"] }
bytes = "*"
async-trait = "*"

wasmtime = { version = "^13", features = ["component-model"] }
wasmtime-wasi = "^13"
